<?php
return [
'name' => 'Nibble Electronica',
'website' => 'http://127.0.0.1:8081',
'company_phone' => '22222222',
'email_from' => 'noreply@nibble.cl',
'maintenance_mode' => '0',
'currency' => 'L',
'shop_min_amount' => '100',
'shipping_method' => '2',
'shipping_default_value' => '50.00',
'shipping_amount_min' => '500',
'to_go' => '1',
'social_facebook' => '#',
'social_instagram' => '#',
'social_twitter' => '#',
'social_youtube' => '#',
'social_whatsapp' => '#',
'payment_method_cash' => '1',
'payment_method_transfer' => '1',
'payment_method_paypal' => '1',
'payment_method_credit_card' => '1',
'products_per_page' => '5',
'products_per_page_random' => '10',
'server_uploads_paths' => 'C:/www/md/madecms/public/uploads',
'server_uploads_user_paths' => 'C:/www/md/madecms/public/uploads_users',
'server_webapp_path' => 'c:/www/md/madecms_pwa/',
]
?>
