<?php
return [
'name' => 'Nibble Electronica',
'website' => 'http://127.0.0.1:8000',
'company_phone' => '22222222',
'email_from' => 'noreply@nibble.cl',
'maintenance_mode' => '0',
'currency' => 'CLP',
'shop_min_amount' => '100',
'shipping_method' => '0',
'shipping_default_value' => '50.00',
'shipping_amount_min' => '500',
'to_go' => '0',
'social_facebook' => 'https://www.facebook.com/nibble.cl/',
'social_instagram' => 'https://www.instagram.com/nibble.cl/?hl=es',
'social_twitter' => '#',
'social_youtube' => '#',
'social_whatsapp' => '#',
'payment_method_cash' => '1',
'payment_method_transfer' => '1',
'payment_method_paypal' => '0',
'payment_method_credit_card' => '0',
'products_per_page' => '5',
'products_per_page_random' => '10',
'server_uploads_paths' => 'C:\Users\migue\Downloads\madecms/public',
'server_uploads_user_paths' => 'C:\Users\migue\Downloads\madecms\public',
'server_webapp_path' => 'C:\Users\migue\Downloads\madecms',
]
?>
